# Base Project Configuration
base:
  project_name: "audio_classifier"
  random_state: 42

# Data Paths (relative to project root)
data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  features_path: "data/features"
  model_dir: "models"
  log_dir: "logs"  # <-- ADD THIS LINE

# Audio Preprocessing Parameters
preprocessing:
  sample_rate: 16000
  duration_seconds: 5
  
# Feature Extraction Parameters
features:
  n_mels: 128      # Number of Mel bands to generate
  n_fft: 2048      # Length of the FFT window
  hop_length: 512  # Number of samples between successive frames